spring:
  datasource:
    url: jdbc:postgresql://ooad-scenes-4187.7s5.aws-ap-south-1.cockroachlabs.cloud:26257/defaultdb?sslmode=verify-full&password=FQD0SLPTGhkG02qsrMiJgQ&user=anonimoose
    username: anonimoose
    password: FQD0SLPTGhkG02qsrMiJgQ
